import React, { useState, useEffect } from 'react';
import { 
  Calendar, 
  CalendarDays,
  Plus, 
  Trash2, 
  Check, 
  Clock, 
  Sliders, 
  X, 
  Play, 
  Pause, 
  RefreshCcw, 
  Flame, 
  AlertCircle,
  Tag,
  ArrowUpRight,
  ArrowDownRight,
  Sparkles,
  DollarSign
} from 'lucide-react';
import { RecurringTransaction, Category, Transaction, RecurrenceInterval, TransactionType } from '../types';

interface RecurringViewProps {
  apiFetch: (endpoint: string, options?: RequestInit) => Promise<any>;
  categories: Category[];
  currencySymbol: string;
  onRefreshFinanceData: () => void;
}

export default function RecurringView({ 
  apiFetch, 
  categories, 
  currencySymbol,
  onRefreshFinanceData
}: RecurringViewProps) {
  const [recurringTransactions, setRecurringTransactions] = useState<RecurringTransaction[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<{ text: string; type: 'success' | 'info' | 'error' } | null>(null);

  // Form State
  const [showAddForm, setShowAddForm] = useState(false);
  const [type, setType] = useState<TransactionType>('expense');
  const [amount, setAmount] = useState('');
  const [category, setCategory] = useState('');
  const [interval, setIntervalVal] = useState<RecurrenceInterval>('monthly');
  const [startDate, setStartDate] = useState(() => new Date().toISOString().split('T')[0]);
  const [nextDueDate, setNextDueDate] = useState(() => {
    const nextMonth = new Date();
    nextMonth.setMonth(nextMonth.getMonth() + 1);
    return nextMonth.toISOString().split('T')[0];
  });
  const [notes, setNotes] = useState('');
  const [tagsInput, setTagsInput] = useState('');

  // Processing triggers
  const [processing, setProcessing] = useState(false);

  // Load schedules
  const loadSchedules = async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await apiFetch('/api/recurring-transactions');
      setRecurringTransactions(data.recurringTransactions || []);
      
      if (data.autoGeneratedCount > 0) {
        showFlashMessage(
          `Cron-like scheduler automatically triggered: Built ${data.autoGeneratedCount} transaction logs matching schedule rules.`,
          'success'
        );
        onRefreshFinanceData();
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Unable to load scheduled repeating transaction configurations.');
    } finally {
      setLoading(false);
    }
  };

  const showFlashMessage = (text: string, type: 'success' | 'info' | 'error' = 'success') => {
    setMessage({ text, type });
    setTimeout(() => setMessage(null), 5000);
  };

  useEffect(() => {
    loadSchedules();
  }, []);

  const handleCreateSchedule = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!amount || isNaN(Number(amount)) || Number(amount) <= 0) {
      showFlashMessage('Please specify a positive numerical payment amount.', 'error');
      return;
    }
    if (!category) {
      showFlashMessage('Please select a visual categorisation label.', 'error');
      return;
    }
    if (!nextDueDate) {
      showFlashMessage('Please configure the direct incoming Next Due Date trigger.', 'error');
      return;
    }

    try {
      setProcessing(true);
      const processedTags = tagsInput
        .split(',')
        .map(t => t.trim())
        .filter(t => t.length > 0);

      await apiFetch('/api/recurring-transactions', {
        method: 'POST',
        body: JSON.stringify({
          type,
          amount: Number(amount),
          category,
          interval,
          startDate,
          nextDueDate,
          notes,
          tags: processedTags
        })
      });

      showFlashMessage('Repeating transaction schedule recorded successfully! The internal cron generator evaluated the parameters.');
      setShowAddForm(false);
      resetForm();
      await loadSchedules();
      onRefreshFinanceData(); // updates the overall networth dashboard counters
    } catch (err: any) {
      showFlashMessage(err.message || 'Failed to initialize repeat rule configuration parameters.', 'error');
    } finally {
      setProcessing(false);
    }
  };

  const resetForm = () => {
    setAmount('');
    setCategory('');
    setIntervalVal('monthly');
    setStartDate(new Date().toISOString().split('T')[0]);
    const nextMonth = new Date();
    nextMonth.setMonth(nextMonth.getMonth() + 1);
    setNextDueDate(nextMonth.toISOString().split('T')[0]);
    setNotes('');
    setTagsInput('');
  };

  const handleToggleActive = async (rt: RecurringTransaction) => {
    try {
      const updatedStatus = !rt.isActive;
      await apiFetch(`/api/recurring-transactions/${rt.id}`, {
        method: 'PUT',
        body: JSON.stringify({ isActive: updatedStatus })
      });
      
      showFlashMessage(
        updatedStatus 
          ? `Activated "${rt.category}" subscription schedule. Trigger checks are back life!`
          : `Paused "${rt.category}" schedule rules. Automatic creation is suspended.`,
        'info'
      );
      await loadSchedules();
    } catch (err: any) {
      showFlashMessage(err.message || 'Unable to lock active claim.', 'error');
    }
  };

  const handleDeleteSchedule = async (id: string, label: string) => {
    if (!confirm(`Are you absolutely sure you want to delete the scheduled recurring transaction rule for "${label}"? This will stop upcoming generation events completely.`)) {
      return;
    }

    try {
      await apiFetch(`/api/recurring-transactions/${id}`, {
        method: 'DELETE'
      });
      showFlashMessage(`Successfully removed configuration details for "${label}".`, 'success');
      await loadSchedules();
    } catch (err: any) {
      showFlashMessage(err.message || 'Unable to erase target record.', 'error');
    }
  };

  const handleManualCronTrigger = async () => {
    try {
      setProcessing(true);
      const res = await apiFetch('/api/recurring-transactions/trigger-process', {
        method: 'POST'
      });

      if (res.generatedCount > 0) {
        showFlashMessage(
          `Success! The cron utility identified and finalized ${res.generatedCount} transactions matching pending dates.`,
          'success'
        );
        onRefreshFinanceData();
        await loadSchedules();
      } else {
        showFlashMessage('Processed. No active schedules are currently due or past due for generation.', 'info');
      }
    } catch (err: any) {
      showFlashMessage(err.message || 'Error occurred while executing manual query triggers.', 'error');
    } finally {
      setProcessing(false);
    }
  };

  // Calculations
  const activeSchedules = recurringTransactions.filter(rt => rt.isActive);
  const totalMonthlyCommitment = activeSchedules.reduce((sum, rt) => {
    let monthlyAmount = rt.amount;
    // Calculate estimated monthly equivalent burden
    if (rt.interval === 'daily') {
      monthlyAmount = rt.amount * 30;
    } else if (rt.interval === 'weekly') {
      monthlyAmount = rt.amount * 4.33;
    } else if (rt.interval === 'yearly') {
      monthlyAmount = rt.amount / 12;
    }
    return sum + (rt.type === 'expense' ? monthlyAmount : -monthlyAmount);
  }, 0);

  // Find standard categories filtered by flow type
  const activeCategories = categories.filter(c => c.type === type);

  return (
    <div className="space-y-8 animate-fade-in" id="recurring-payments-block">
      {/* Module Title Banner */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between border-b border-slate-200 pb-5">
        <div>
          <div className="flex items-center gap-2.5">
            <div className="bg-blue-50 text-blue-600 p-2 rounded-lg border border-blue-100">
              <CalendarDays className="h-6 w-6" />
            </div>
            <h2 className="text-2xl font-bold tracking-tight text-slate-900 font-sans">Recurring Payments</h2>
          </div>
          <p className="text-sm text-slate-500 mt-1">
            Automate your repeated utilities, subscriptions, and paychecks. The system executes background cron cycles to post transactions on exact due dates.
          </p>
        </div>
        <div className="flex items-center gap-2.5">
          <button
            onClick={handleManualCronTrigger}
            disabled={processing}
            className="flex items-center gap-1.5 rounded-lg border border-slate-250 bg-white text-slate-700 hover:bg-slate-50 px-4 py-2 text-xs font-bold font-sans transition-all cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed select-none"
            title="Execute cron system processor rule matching now"
          >
            <RefreshCcw className={`h-4 w-4 ${processing ? 'animate-spin' : ''}`} />
            <span>Run Cron Scheduler</span>
          </button>
          <button
            onClick={() => {
              setShowAddForm(!showAddForm);
              if (categories.length > 0 && !category) {
                setCategory(categories[0].name);
              }
            }}
            className="flex items-center gap-1.5 rounded-lg bg-blue-600 text-white hover:bg-blue-700 px-4 py-2 text-xs font-bold font-sans transition-all cursor-pointer shadow-sm shadow-blue-500/10"
          >
            {showAddForm ? <X className="h-4 w-4" /> : <Plus className="h-4 w-4" />}
            <span>{showAddForm ? 'Close Wizard' : 'Schedule Custom Payment'}</span>
          </button>
        </div>
      </div>

      {/* Messages */}
      {message && (
        <div className={`p-4 rounded-xl border text-xs font-semibold flex items-center gap-3 shadow-xs animate-fade-in ${
          message.type === 'success' 
            ? 'bg-emerald-50 border-emerald-150 text-emerald-800' 
            : message.type === 'error'
              ? 'bg-rose-50 border-rose-150 text-rose-800'
              : 'bg-indigo-50 border-indigo-150 text-indigo-800'
        }`}>
          {message.type === 'error' ? (
            <AlertCircle className="h-4 w-4 shrink-0" />
          ) : (
            <Sparkles className="h-4 w-4 text-emerald-600 shrink-0" />
          )}
          <span>{message.text}</span>
        </div>
      )}

      {/* Dashboard KPI Summary Boxes */}
      <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <div className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block">Monthly Equivalent Cashflow</span>
            <span className="bg-amber-50 border border-amber-100 text-amber-700 text-[10px] font-bold px-2 py-0.5 rounded-full">Burden Estimate</span>
          </div>
          <p className="text-2xl font-bold mt-3 text-slate-900">
            {totalMonthlyCommitment >= 0 ? '-' : '+'}
            {currencySymbol}
            {Math.abs(totalMonthlyCommitment).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </p>
          <span className="text-[10px] text-slate-500 font-semibold mt-1.5 block leading-relaxed">
            Computed on Active contracts scaled to absolute 30-day intervals
          </span>
        </div>

        <div className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block font-sans">Active Schedules</span>
            <Clock className="h-4 w-4 text-blue-500" />
          </div>
          <p className="text-2xl font-bold mt-3 text-slate-900">
            {activeSchedules.length} / {recurringTransactions.length}
          </p>
          <span className="text-[10px] text-slate-400 font-semibold mt-1.5 block">
            Paused items do not generate temporary ledger events
          </span>
        </div>

        <div className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm bg-gradient-to-br from-indigo-50/40 to-blue-50/20 border-indigo-100/40">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block font-sans">Daemon Status</span>
            <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" title="System background listener online" />
          </div>
          <p className="text-lg font-bold mt-2 text-indigo-950 flex items-center gap-1.5">
            <span>Dynamic Cron Active</span>
          </p>
          <span className="text-[10px] text-indigo-805/80 font-bold mt-1.5 block leading-relaxed">
            Interval rules are checked every 3 minutes. Generated logs are tagged automatically.
          </span>
        </div>
      </div>

      {/* Add Form Wizard Panel */}
      {showAddForm && (
        <form onSubmit={handleCreateSchedule} className="bg-white border text-xs border-slate-150 rounded-xl p-6 shadow-sm space-y-5 animate-fade-in">
          <div className="border-b border-slate-100 pb-3 flex items-center justify-between">
            <div>
              <h3 className="text-sm font-bold text-slate-900 font-sans">Add Repeating Transaction Schedule</h3>
              <p className="text-[11px] text-slate-500 mt-0.5">Build a rule system detailing automated ledger triggers</p>
            </div>
            <button
              type="button"
              onClick={() => setShowAddForm(false)}
              className="text-slate-400 hover:text-slate-600 p-1.5 hover:bg-slate-50 rounded"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {/* Cashflow Type */}
            <div className="space-y-1.5">
              <label className="block text-[11px] font-bold text-slate-600 uppercase tracking-wide">Type</label>
              <div className="grid grid-cols-2 gap-1 bg-slate-50 p-1 rounded-lg border border-slate-200">
                <button
                  type="button"
                  onClick={() => {
                    setType('expense');
                    const expCats = categories.filter(c => c.type === 'expense');
                    if (expCats.length > 0) setCategory(expCats[0].name);
                  }}
                  className={`py-1.5 text-center text-[10px] font-bold rounded cursor-pointer transition-all ${
                    type === 'expense' 
                      ? 'bg-white text-slate-900 shadow-xs border border-slate-200/40' 
                      : 'text-slate-500 hover:text-slate-800'
                  }`}
                >
                  Expense Schedule
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setType('income');
                    const incCats = categories.filter(c => c.type === 'income');
                    if (incCats.length > 0) setCategory(incCats[0].name);
                  }}
                  className={`py-1.5 text-center text-[10px] font-bold rounded cursor-pointer transition-all ${
                    type === 'income' 
                      ? 'bg-white text-slate-900 shadow-xs border border-slate-200/40' 
                      : 'text-slate-500 hover:text-slate-800'
                  }`}
                >
                  Income Schedule
                </button>
              </div>
            </div>

            {/* Currency Amount */}
            <div className="space-y-1.5">
              <label className="block text-[11px] font-bold text-slate-600 uppercase tracking-wide">Amount ({currencySymbol})</label>
              <div className="relative">
                <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-slate-400 font-bold">$</span>
                <input
                  type="number"
                  step="0.01"
                  required
                  placeholder="0.00"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  className="w-full bg-white border border-slate-200 rounded-lg py-2 pl-7 pr-3 text-slate-800 font-sans font-bold focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-550"
                />
              </div>
            </div>

            {/* Interval */}
            <div className="space-y-1.5">
              <label className="block text-[11px] font-bold text-slate-600 uppercase tracking-wide">Recurrence Interval</label>
              <select
                value={interval}
                onChange={(e) => setIntervalVal(e.target.value as RecurrenceInterval)}
                className="w-full bg-white border border-slate-200 cursor-pointer rounded-lg px-3 py-2 text-slate-800 font-bold focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="daily">Daily Loop</option>
                <option value="weekly">Weekly Cycle</option>
                <option value="monthly">Monthly Subscription</option>
                <option value="yearly">Yearly Obligation</option>
              </select>
            </div>

            {/* Category selection */}
            <div className="space-y-1.5">
              <label className="block text-[11px] font-bold text-slate-600 uppercase tracking-wide">Category Category</label>
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className="w-full bg-white border border-slate-200 cursor-pointer rounded-lg px-3 py-2 text-slate-800 font-bold focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
              >
                {activeCategories.map((cat) => (
                  <option key={cat.id} value={cat.name}>
                    {cat.name}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {/* Start Date */}
            <div className="space-y-1.5">
              <label className="block text-[11px] font-bold text-slate-600 uppercase tracking-wide">Contract Start Date</label>
              <input
                type="date"
                required
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full bg-white border border-slate-200 rounded-lg px-3 py-2 font-bold text-slate-800 focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
            </div>

            {/* First Next Due triggers */}
            <div className="space-y-1.5">
              <label className="block text-[11px] font-bold text-slate-600 uppercase tracking-wide">First / Next Due Date</label>
              <input
                type="date"
                required
                value={nextDueDate}
                onChange={(e) => setNextDueDate(e.target.value)}
                className="w-full bg-white border border-slate-200 rounded-lg px-3 py-2 font-bold text-slate-800 focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
            </div>

            {/* Dynamic Custom Tags */}
            <div className="space-y-1.5">
              <label className="block text-[11px] font-bold text-slate-600 uppercase tracking-wide">Automation Tags (Comma Separated)</label>
              <input
                type="text"
                placeholder="utility, rent, netflix"
                value={tagsInput}
                onChange={(e) => setTagsInput(e.target.value)}
                className="w-full bg-white border border-slate-200 rounded-lg px-3 py-2 text-slate-800 font-bold focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
            </div>
          </div>

          {/* Description */}
          <div className="space-y-1.5">
            <label className="block text-[11px] font-bold text-slate-600 uppercase tracking-wide">Narrative / Custom Notes</label>
            <input
              type="text"
              placeholder="e.g. Landlord monthly apartment rent direct debit"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="w-full bg-white border border-slate-200 rounded-lg px-3 py-2 text-slate-800 focus:outline-none focus:ring-1 focus:ring-blue-500"
            />
          </div>

          <div className="flex items-center justify-end gap-2 pt-2">
            <button
              type="button"
              onClick={resetForm}
              className="px-4 py-2 border rounded-lg border-slate-250 hover:bg-slate-50 font-bold font-sans cursor-pointer text-slate-700"
            >
              Clear
            </button>
            <button
              type="submit"
              disabled={processing}
              className="px-5 py-2 rounded-lg bg-blue-600 text-white font-bold font-sans hover:bg-blue-700 cursor-pointer shadow-sm disabled:opacity-40"
            >
              {processing ? 'Processing Scheduler...' : 'Commit schedule rule'}
            </button>
          </div>
        </form>
      )}

      {/* Main List Grid of Scheduled Items */}
      <div className="bg-white border rounded-xl border-slate-100 shadow-sm overflow-hidden p-6 space-y-4">
        <div>
          <h3 className="text-base font-bold text-slate-900 font-sans flex items-center gap-2">
            <Sliders className="h-4 w-4 text-indigo-500" />
            <span>Active Subscription & Commitments Manifest</span>
          </h3>
          <p className="text-xs text-slate-500 mt-1">
            Monitor and suspend active rule systems. If a date is past due, click <strong>"Run Cron Scheduler"</strong> above to force immediate catchup.
          </p>
        </div>

        {loading ? (
          <div className="flex flex-col items-center justify-center py-12 text-slate-450 space-y-3">
            <RefreshCcw className="h-8 w-8 text-blue-500 animate-spin" />
            <p className="text-xs font-semibold">Contacting ledger cluster config streams...</p>
          </div>
        ) : recurringTransactions.length === 0 ? (
          <div className="text-center py-14 space-y-3 border border-dashed rounded-xl border-slate-200 bg-slate-50/20">
            <Calendar className="h-10 w-10 text-slate-300 mx-auto" strokeWidth={1.5} />
            <div className="space-y-1">
              <h4 className="text-xs font-bold text-slate-800">No Recurring Schedules Configured</h4>
              <p className="text-[11px] text-slate-500">Simplify budgeting by adding regular outgoings or salary paychecks.</p>
            </div>
            <button
              onClick={() => {
                setShowAddForm(true);
                if (categories.length > 0 && !category) {
                  setCategory(categories[0].name);
                }
              }}
              className="inline-flex items-center gap-1 bg-blue-50 text-blue-600 hover:bg-blue-100 border border-blue-105 rounded px-3 py-1.5 text-[10px] font-bold"
            >
              <Plus className="h-3 w-3" />
              <span>Create first rule</span>
            </button>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-100 font-bold uppercase tracking-wider text-slate-450 text-[10px]">
                  <th className="py-3 px-4">Recurrent Title</th>
                  <th className="py-3 px-4">Cycle</th>
                  <th className="py-3 px-4 text-right">Commitment</th>
                  <th className="py-3 px-4 text-center">First Date</th>
                  <th className="py-3 px-4 text-center text-indigo-900">Next Occurrence</th>
                  <th className="py-3 px-4">Status</th>
                  <th className="py-3 px-4 text-center rounded-r-md">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100/60 font-medium text-slate-700">
                {recurringTransactions.map((rt) => {
                  return (
                    <tr key={rt.id} className={`hover:bg-slate-50/30 transition-colors ${!rt.isActive ? 'opacity-65 bg-slate-100/20' : ''}`}>
                      {/* Name / Category */}
                      <td className="py-3.5 px-4">
                        <div className="flex items-center gap-2.5">
                          <div className={`p-1.5 rounded-lg border ${
                            rt.type === 'income' 
                              ? 'bg-emerald-50 text-emerald-600 border-emerald-100' 
                              : 'bg-rose-50 text-rose-600 border-rose-100'
                          }`} title={rt.type === 'income' ? 'Salary / Cashflow credit' : 'Automatic charge debit'}>
                            {rt.type === 'income' ? <ArrowUpRight className="h-4 w-4" /> : <ArrowDownRight className="h-4 w-4" />}
                          </div>
                          <div>
                            <div className="font-bold text-slate-900 flex items-center gap-1.5">
                              <span>{rt.category}</span>
                              <span className="text-[10px] font-normal text-slate-400 font-mono">({rt.id})</span>
                            </div>
                            {rt.notes && <p className="text-[10px] text-slate-450 mt-0.5 line-clamp-1 max-w-[220px]">{rt.notes}</p>}
                            
                            {/* Tags list */}
                            {rt.tags && rt.tags.length > 0 && (
                              <div className="flex flex-wrap items-center gap-1.5 mt-1.5">
                                {rt.tags.map(t => (
                                  <span key={t} className="inline-flex items-center gap-0.5 text-[9px] bg-slate-100 px-1.5 py-0.2 rounded border text-slate-500 font-semibold">
                                    <Tag className="h-2 w-2" />
                                    <span>{t}</span>
                                  </span>
                                ))}
                              </div>
                            )}
                          </div>
                        </div>
                      </td>

                      {/* Recurrence Pattern */}
                      <td className="py-3.5 px-4 font-bold text-slate-800 uppercase text-[10px] tracking-wide">
                        {rt.interval === 'daily' && 'Daily'}
                        {rt.interval === 'weekly' && 'Weekly'}
                        {rt.interval === 'monthly' && 'Monthly'}
                        {rt.interval === 'yearly' && 'Yearly'}
                      </td>

                      {/* Cash value */}
                      <td className={`py-3.5 px-4 text-right font-sans font-bold text-sm ${
                        rt.type === 'income' ? 'text-emerald-600' : 'text-rose-600'
                      }`}>
                        {rt.type === 'income' ? '+' : '-'}
                        {currencySymbol}
                        {rt.amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                      </td>

                      {/* First generated start */}
                      <td className="py-3.5 px-4 text-center font-mono text-[10.5px] text-slate-450">
                        {rt.startDate}
                      </td>

                      {/* Next occurrence date */}
                      <td className="py-3.5 px-4 text-center">
                        <div className="inline-block relative">
                          <span className={`font-mono text-[11px] font-bold px-2 py-0.5 rounded border ${
                            rt.isActive 
                              ? 'bg-blue-50 border-blue-100 text-blue-750' 
                              : 'bg-slate-100 border-slate-200 text-slate-450'
                          }`}>
                            {rt.nextDueDate}
                          </span>
                        </div>
                      </td>

                      {/* Toggle engine controller */}
                      <td className="py-3.5 px-4">
                        <button
                          onClick={() => handleToggleActive(rt)}
                          className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-bold cursor-pointer transition-all border ${
                            rt.isActive
                              ? 'bg-emerald-50 text-emerald-700 border-emerald-100 hover:bg-emerald-100'
                              : 'bg-amber-50 text-amber-700 border-amber-100 hover:bg-amber-100'
                          }`}
                        >
                          {rt.isActive ? <Play className="h-2.5 w-2.5" /> : <Pause className="h-2.5 w-2.5" />}
                          <span>{rt.isActive ? 'Active' : 'Paused'}</span>
                        </button>
                      </td>

                      {/* Wipe schedule */}
                      <td className="py-3.5 px-4 text-center">
                        <button
                          onClick={() => handleDeleteSchedule(rt.id, rt.category)}
                          className="p-1 px-[7px] text-rose-500 rounded bg-rose-50 hover:bg-rose-100 border border-rose-100 transition-colors select-none cursor-pointer"
                          title="Erase repetitive configuration"
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Narrative Documentation Information */}
      <div className="bg-slate-50 border border-slate-150 p-5 rounded-xl flex gap-3 text-xs leading-relaxed text-slate-550">
        <Sliders className="h-5 w-5 text-blue-500 shrink-0 mt-0.5" />
        <div>
          <strong className="text-slate-800 block mb-1">Functional Architecture Information:</strong>
          Our cron-like automation is designed to avoid duplications while catching up if your browser is closed for days! For example, if rent is due on the 1st of each month, and you log in on the 3rd, VaultFlow identifies the delay, safely generates the real payment entries dated the 1st, and increments the Next Due date pointer to the 1st of the following month automatically. Pause schedules to safely stop scheduled payments from logging.
        </div>
      </div>
    </div>
  );
}
